- hosts: minecraft
  become: yes
  tasks:
    - name: Update and upgrade yum packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull Minecraft Docker image
      docker_image:
        name: itzg/minecraft-server
        source: pull

    - name: Run Minecraft Docker container
      docker_container:
        name: minecraft-server
        image: itzg/minecraft-server
        state: started
        restart_policy: always
        ports:
          - "25565:25565"
        env:
          EULA: "TRUE"

    - name: Configure Minecraft server auto-restart
      copy:
        dest: /etc/systemd/system/minecraft-server.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=docker.service
          Requires=docker.service

          [Service]
          Restart=always
          ExecStart=/usr/bin/docker start -a minecraft-server
          ExecStop=/usr/bin/docker stop -t 2 minecraft-server

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Minecraft server service
      systemd:
        name: minecraft-server
        enabled: yes
        state: started
