- hosts: minecraft
  become: yes
  gather_facts: yes
  tasks:
    - name: Ensure Python 3 is installed
      raw: |
        amazon-linux-extras install python3 -y || \
        yum install python3 -y
      changed_when: false

    - name: Ensure pip3 is installed
      raw: |
        curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
        python3 get-pip.py
      changed_when: false

    - name: Ensure pip3 is in the PATH
      raw: |
        ln -s /usr/local/bin/pip3 /usr/bin/pip3 || true
      changed_when: false

    - name: Install Ansible and required Python packages
      raw: |
        pip3 install ansible requests urllib3==1.26.5
      changed_when: false

    - name: Update and upgrade yum packages
      command: yum update -y

    - name: Install Docker
      command: yum install -y docker

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull Minecraft Docker image
      community.docker.docker_image:
        name: itzg/minecraft-server
        source: pull

    - name: Run Minecraft Docker container
      community.docker.docker_container:
        name: minecraft-server
        image: itzg/minecraft-server
        state: started
        restart_policy: always
        ports:
          - "25565:25565"
        env:
          EULA: "TRUE"

    - name: Configure Minecraft server auto-restart
      copy:
        dest: /etc/systemd/system/minecraft-server.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=docker.service
          Requires=docker.service

          [Service]
          Restart=always
          ExecStart=/usr/bin/docker start -a minecraft-server
          ExecStop=/usr/bin/docker stop -t 2 minecraft-server

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable Minecraft server service
      service:
        name: minecraft-server
        enabled: yes
